server:
  port: 8123


spring:
  datasource:
    url: jdbc:mysql://aixiaolin.cn:3306/test?useSSL=false&useUnicode=true
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.example.pojo

